### ISSUE TITLE
SHA256 for MicroMamba 0.27.0 artifact on linux x86-64 is wrong

### ISSUE THREAD

**Issue by kshyatt** [cjdoris/MicroMamba.jl#9]
I'm getting a hash mismatch. When I download the tarball and `shasum` it myself I get `"1b1bdd07..."` rather than `"4adbf3091a4159af2c48264a8e32ecb98147b0e3f200601f384f8f53a6910ca2"`

**Comment by giordano** [comment]
CC @cjdoris (since [you aren't watching the repository](https://github.com/cjdoris/MicroMamba.jl/watchers)).  This is probably not your fault (it'd appear the upstream tarballs have been changed in-place, which is bad), but this is breaking many downstream packages.

**Comment by Lightup1** [comment]
On windows
```
┌ Error: Hash Mismatch!
│   Expected sha256:   358de7998dc768d3db44f1ac0791a39c73c068920fa618849633ec183f2ab380
│   Calculated sha256: 8f494ee2b6e6e36a9e81a3b764cf180adb6ad61d1e7901168c44d8a9e2f2ce83
```

**Comment by Lightup1** [comment]
I'm currently using `pythoncall` and there is an error like this.

**Comment by kshyatt** [comment]
@Lightup1 can you see if my PR fixes your issue?

**Comment by Lightup1** [comment]
@kshyatt Your PR works on my case！
Nice!

**Comment by ericphanson** [comment]
I propose we yank MicroMamba v0.1.10 from General, as a workaround to this issue. That doesn’t really address the core problem (unstable URLs) but does work around it, bc 0.1.9 only has older releases of MicroMamba who’s URLs have not changed (and probably won’t for awhile since presumably they aren’t still building them?).

Bc currently the release is broken, and having MicroMamba v0.1.10 anywhere in your dependency tree breaks everything.

**Comment by cjdoris** [comment]
Fixed now thanks. As a longer term solution, I'm going to use `micromamba_jll` instead of grabbing the executable straight from conda.
